#!/usr/bin/env bash

set -e

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

wp_ver=$1

url="https://raw.githubusercontent.com/WordPress/WordPress/${wp_ver}/wp-config-sample.php"

array=(
    "./orig/wp-config-sample.php::${url}"
)

outdated=0

get_md5() {
    if hash md5sum 2>/dev/null; then
        md5sum "$@"
    else
        md5 "$@"
    fi
}

for index in "${array[@]}" ; do
    local="${index%%::*}"
    remote="${index##*::}"

    md5_local=$(cat "${local}" | get_md5)
    md5_remote=$(wget -qO- "${remote}" | get_md5)

    echo "Checking ${local}"

    if [[ "${md5_local}" != "${md5_remote}" ]]; then
        echo "!!! OUTDATED"
        echo "${remote}"
        outdated=1
    else
        echo "OK"
    fi
done

[[ "${outdated}" == 0 ]] || exit 1