name: Build
description: Build WordPress image
inputs:
  version:
    description: drupal version
    required: true
  php_ver:
    description: php version
    required: true
  tags:
    description: image tags
    required: true
  platform:
    description: docker platform
    required: false
    default: linux/amd64
runs:
  using: "composite"
  steps:
  - name: Build image
    env:
      WORDPRESS_VER: ${{ inputs.version }}
      PHP_VER: ${{ inputs.php_ver }}
      TAGS: ${{ inputs.tags }}
      PLATFORM: ${{ inputs.platform }}
    run: |
      set -e
      make buildx-build-amd64
      make
      make buildx-build
      . $GITHUB_ACTION_PATH/release.sh
    shell: bash
