#!/usr/bin/env bash

set -e

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

if [[ ! -f "${APP_ROOT}/index.php" ]]; then
    echo "WordPress not found in ${APP_ROOT} - copying now..."
    rsync -a "/usr/src/wordpress/" "${APP_ROOT}/"
    echo "Complete! WordPress has been successfully copied to ${APP_ROOT}"

    if [[ -z "${WODBY_APP_NAME}" ]]; then
        su-exec wodby cp "${APP_ROOT}/wp-config-sample.php" "${APP_ROOT}/wp-config.php"
        sed -i "s/database_name_here/${DB_NAME:-wordpress}/" "${APP_ROOT}/wp-config.php"
        sed -i "s/username_here/${DB_NAME:-wordpress}/" "${APP_ROOT}/wp-config.php"
        sed -i "s/password_here/${DB_NAME:-wordpress}/" "${APP_ROOT}/wp-config.php"
        sed -i "s/'DB_HOST', 'localhost'/'DB_HOST', '${DB_NAME:-mariadb}'/" "${APP_ROOT}/wp-config.php"
        echo "define('FS_METHOD', 'direct');" >> "${APP_ROOT}/wp-config.php"
    fi
else
    latest_ver=$(su-exec wodby wp core version --path=/usr/src/wordpress)
    current_ver=$(su-exec wodby wp core version --path="${APP_ROOT}")

    res=$(compare-semver.sh "${latest_ver}" "${current_ver}" ">")

    if [[ "${res}" == 0 ]]; then
        echo "Current version ${current_ver} is outdated, updating to ${latest_ver}..."
        rsync -a "/usr/src/wordpress/" "${APP_ROOT}/"
        echo "Complete! WordPress has been successfully updated to ${latest_ver}"
    fi
fi
